### ISSUE TITLE
Deleting connected components from rossystem

### ISSUE THREAD

**Issue by ipa-cmh** [ipa320/ros-model#134]
Deleting connected components from a .rossystem file via the Sirius interface seems to be not working.
I have tried it with a simple model of turtlebot3:

![Prior to deletion](https://user-images.githubusercontent.com/51296695/119639085-8b911b00-be17-11eb-84b0-701ec8954974.PNG)

When deleting the turtlebot3_core_node the connections this shows up in the graphical view:
![After deletion](https://user-images.githubusercontent.com/51296695/119639255-b9765f80-be17-11eb-9e42-4d7c46044b09.PNG)

It seems to be right, but when trying to save, the folowing mesage shows up:
![Error message](https://user-images.githubusercontent.com/51296695/119639329-cb580280-be17-11eb-8cd7-3e7772b61278.PNG)

To me it seems the changes are not reflected in the .rossystem file or the connections are not deleted with the component.

**Comment by ipa-nhg** [comment]
Thanks for the detailed report 👍🏽 

Very likely it is because of the connections. For that I am using the standard plugins of Sirius but it seems like these plugins are not taking into account the references interfaces.

To solve this I will have to create a new Java Action that can be triggered from Sirius to remove component cleanly. This action should have the same structure than this examples: https://github.com/ipa320/ros-model/tree/master/plugins/de.fraunhofer.ipa.ros.sirius/src/de/fraunhofer/ipa/ros/sirius

**Comment by ipa-nhg** [comment]
Solved by https://github.com/ipa320/ros-model/pull/137
