### ISSUE TITLE
Problems with runing de.fraunhofer.ipa.ros.plugin

### ISSUE THREAD

**Issue by roman-pr94** [ipa320/ros-model#89]
Followed the installation instruction I can say that first Option does not work for me at all,
But with Option 2 I also have a problem.

I test several versions of Eclipse in different combinations of Java versions. I get succeed compiling on Java 8 and Eclipse 2019-06 with all the components as on the image https://github.com/ipa320/ros-model#0-start-the-ros-tooling-application.
But when I am trying to run de.fraunhofer.ipa.ros.plugin component I getting this error:
![Eclipse_compilation_issue](https://user-images.githubusercontent.com/58513457/70724986-860f4600-1cf3-11ea-8f38-4ece92bedcb4.png)
Also, I have this validation window, which tells me that one of the packages required  Java 11:
![java_exception](https://user-images.githubusercontent.com/58513457/70724790-23b64580-1cf3-11ea-86eb-65b691248f5e.png)
But I can not compile the project with other versions of Java.

My system settings:
Ubuntu 18
ROS Melodic
java-8-openjdk-amd64/jre
Eclipse 2019-06

Is there is any ideas on how to fix this issue?

**Comment by ipa-nhg** [comment]
Thanks a lot for interest! :)

What was the problem with the first method? I highly recommend it in order to avoid dependency problems (like the one your are getting). The errors you are having are not related to the ros tooling specific software and everything should works although of them, is the tooling being started or not at all?

The setup you describe is completely fine, Thanks for pointing this, I will update the documentation to specify the right java package version.

**Comment by roman-pr94** [comment]
The problem with the first Option is that when I add new repisitory I do not have any components finde on the list:
![Screenshot from 2019-12-13 12-13-19](https://user-images.githubusercontent.com/58513457/70799644-1dcb6d80-1da2-11ea-84e3-a5a085374afd.png)
Which means that I can not install these packages :/

**Comment by ipa-nhg** [comment]
Please uncheck the option 
`- Group items by category`

**Comment by roman-pr94** [comment]
Yes, it is working now but only with Java 11.
Thank you Nadia!

**Comment by ipa-nhg** [comment]
Thanks, I fixed the documentation https://github.com/ipa320/ros-model/pull/90
